
--SELECT * 
--FROM PROJECT2.DBO.[2015] 
--WHERE COUNTRY IS NULL --CA
--OR HAPPINESS_RANK IS NULL--CA
--OR HAPPINESS_SCORE IS NULL--CA
--OR ECONOMY_GDP_PER_CAPITA IS NULL --CA
--OR HEALTH_LIFE_EXPECTANCY IS NULL --CA
--OR FREEDOM IS NULL --CA
--OR TRUST_GOVERNMENT_CORRUPTION IS NULL --CA
--OR GENEROSITY IS NULL --CA
--OR DYSTOPIA_RESIDUAL IS NULL
--OR REGION IS NULL --CA
--OR FAMILY IS NULL
--OR STANDARD_ERROR IS NULL

SELECT * 
FROM PROJECT2.DBO.[2015] 
WHERE COUNTRY IS NULL --CA
OR HAPPINESS_RANK =0 --CA
OR HAPPINESS_SCORE =0 --CA
OR ECONOMY_GDP_PER_CAPITA=0 --CA
OR HEALTH_LIFE_EXPECTANCY =0 --CA
OR FREEDOM =0 --CA
OR TRUST_GOVERNMENT_CORRUPTION =0 --CA
OR GENEROSITY = 0 --CA
OR DYSTOPIA_RESIDUAL =0
OR REGION IS NULL --CA
OR FAMILY =0
OR STANDARD_ERROR =0

-- Generosity value of greece are zero
UPDATE T15
SET  Trust_Government_Corruption =
(( SELECT  Trust_Government_Corruption
FROM Project2.DBO.[2016]
WHERE Country='sundan' )
+
(SELECT  Trust_Government_Corruption
FROM Project2.DBO.[2017]
WHERE Country='sundan')
+
(SELECT PERCEPTIONS_OF_CORRUPTION
FROM Project2.DBO.[2018]
WHERE Country_OR_REGION='sundan')
+
(SELECT  PERCEPTIONS_OF_CORRUPTION
FROM Project2.DBO.[2019]
WHERE Country_OR_REGION='sundan'))/4

FROM Project2.DBO.[2015] T15
WHERE Country='sundan'


SELECT  Generosity
FROM PROJECT2.DBO.[2015]
WHERE COUNTRY='sundan'

SELECT  Generosity
FROM PROJECT2.DBO.[2016]
WHERE COUNTRY='sundan'

SELECT Generosity
FROM PROJECT2.DBO.[2017]
WHERE COUNTRY='sundan'

SELECT Generosity
FROM PROJECT2.DBO.[2018]
WHERE COUNTRY_OR_REGION='sundan'

SELECT Generosity
FROM PROJECT2.DBO.[2019]
WHERE COUNTRY_OR_REGION='sundan'
