
SELECT * 
FROM PROJECT2.DBO.[2016] 
WHERE COUNTRY=NULL --CA
OR HAPPINESS_RANK=0 --CA
OR HAPPINESS_SCORE=0 --CA
OR ECONOMY_GDP_PER_CAPITA=0 --CA
OR HEALTH_LIFE_EXPECTANCY=0 --CA
OR FREEDOM=0 --CA
OR TRUST_GOVERNMENT_CORRUPTION=0 --CA
OR GENEROSITY=0 --CA
OR DYSTOPIA_RESIDUAL=0
OR REGION=NULL  --CA
OR FAMILY=0 
OR UPPER_CONFIDENCE_INTERVAL=0 
OR LOWER_CONFIDENCE_INTERVAL=0


SELECT  Trust_Government_Corruption
FROM PROJECT2.DBO.[2015]
WHERE COUNTRY='Central African Republic'

SELECT  Trust_Government_Corruption
FROM PROJECT2.DBO.[2016]
WHERE COUNTRY='Central African Republic'

SELECT Trust_Government_Corruption
FROM PROJECT2.DBO.[2017]
WHERE COUNTRY='Central African Republic'

SELECT Perceptions_of_corruption
FROM PROJECT2.DBO.[2018]
WHERE COUNTRY_OR_REGION='Central African Republic'

SELECT Perceptions_of_corruption
FROM PROJECT2.DBO.[2019]
WHERE COUNTRY_OR_REGION='Central African Republic'
