
SELECT * 
FROM PROJECT2.DBO.[2017] 
WHERE COUNTRY=NULL  --CA
OR HAPPINESS_RANK=0 --CA
OR HAPPINESS_SCORE=0 --CA
OR ECONOMY_GDP_PER_CAPITA=0 --CA
OR HEALTH_LIFE_EXPECTANCY=0 --CA
OR FREEDOM=0 --CA
OR TRUST_GOVERNMENT_CORRUPTION=0 --CA
OR GENEROSITY=0 --CA
OR DYSTOPIA_RESIDUAL=0
OR WHISKER_HIGH=0 
OR WHISKER_LOW=0
OR FAMILY=0 
OR REGION is NULL


SELECT *
FROM PROJECT2.dbo.[2017]
WHERE REGION IS NULL;

SELECT  Economy_GDP_per_Capita
FROM PROJECT2.DBO.[2015]
WHERE COUNTRY='Central African Republic'

SELECT  Economy_GDP_per_Capita
FROM PROJECT2.DBO.[2016]
WHERE COUNTRY='Central African Republic'

SELECT Economy_GDP_per_Capita
FROM PROJECT2.DBO.[2017]
WHERE COUNTRY='Central African Republic'

SELECT GDP_per_capita
FROM PROJECT2.DBO.[2018]
WHERE COUNTRY_OR_REGION='Central African Republic'

SELECT GDP_per_capita
FROM PROJECT2.DBO.[2019]
WHERE COUNTRY_OR_REGION='Central African Republic'