
SELECT * 
FROM PROJECT2.DBO.[2018] 
WHERE COUNTRY_OR_REGION=NULL  --CA
OR OVERALL_RANK=0 --CA
OR SCORE=0 --CA
OR GDP_PER_CAPITA=0 --CA
OR SOCIAL_SUPPORT=0
OR HEALTHY_LIFE_EXPECTANCY=0 --CA
OR FREEDOM_TO_MAKE_LIFE_CHOICES=0 --CA
OR PERCEPTIONS_OF_CORRUPTION=0 --CA
OR GENEROSITY=0 --CA
OR REGION is NULL  --CA

SELECT *
FROM PROJECT2.dbo.[2018]
WHERE REGION IS NULL;